services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  sqlserver-idp:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStr0ngP@ssword!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata-idp:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStr0ngP@ssword!" -Q "SELECT 1" -C -b
      interval: 10s
      timeout: 5s
      retries: 5

  sqlserver-clubs:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStr0ngP@ssword!"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - sqldata-clubs:/var/opt/mssql
      - ./seedGestionClub.sql:/docker-entrypoint-initdb.d/seedGestionClub.sql:ro
      - ./init-clubs-db.sh:/init-clubs-db.sh:ro
    entrypoint: /bin/bash /init-clubs-db.sh
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStr0ngP@ssword!" -Q "SELECT 1" -C -b
      interval: 10s
      timeout: 5s
      retries: 5

  init-kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c "
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic user-registered --partitions 1 --replication-factor 1 &&
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic user-promoted-to-club-admin --partitions 1 --replication-factor 1 &&
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic user-promoted-to-club-member --partitions 1 --replication-factor 1 &&
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic clubs-topic --partitions 1 --replication-factor 1 &&
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic announcements-topic --partitions 1 --replication-factor 1 &&
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic events-topic --partitions 1 --replication-factor 1 &&
        echo 'All topics created successfully'
      "

  identityprovider:
    build:
      context: ./IdentityProvider
      dockerfile: Dockerfile
    image: mbokri/identityprovider:latest
    ports:
      - "8080:8080"   # HTTP (optionnel, tu peux l'enlever)
      - "8443:8443"   # HTTPS
    depends_on:
      sqlserver-idp:
        condition: service_healthy
      init-kafka:
        condition: service_completed_successfully
    environment:
      Kafka__BootstrapServers: "kafka:29092"
      Kafka__ProducerTopic: "user-registered"
      Kafka__ConsumerTopic: "user-promoted-to-club-admin"
      Kafka__ConsumerGroupId: "identity-provider-group"
      ConnectionStrings__DefaultConnection: "Server=sqlserver-idp;Database=IdentityProvider;User Id=sa;Password=YourStr0ngP@ssword!;TrustServerCertificate=True;"
      JwtOptions__Secret: "votre-secret-de-production-suffisamment-long"
      JwtOptions__Issuer: "myapp"
      JwtOptions__Audience: "myappusers"
      ASPNETCORE_ENVIRONMENT: "Development"
      JwtOptions__ExpirationMinutes: "15"
      JwtOptions__RefreshTokenExpirationDays: "7"
      ASPNETCORE_URLS: "https://+:8443;http://+:8080"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.crt"
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: "/https/aspnetapp.key"
    volumes:
      - keys:/app/keys
      - ./certs:/https:ro # monte le certificat dans le container

  gestionclubs:
    build:
      context: ./GestionClubs
      dockerfile: GestionClubs/Dockerfile
    image: mbokri/gestionclubs:latest
    ports:
      - "8081:8081"   # HTTPS
      - "8082:8080"   # HTTP
    networks:
      - default
      - mynw
    depends_on:
      sqlserver-clubs:
        condition: service_healthy
      identityprovider:
        condition: service_started
      init-kafka:
        condition: service_completed_successfully
    environment:
      Kafka__BootstrapServers: "kafka:29092"
      Kafka__ProducerTopic: "user-promoted-to-club-admin"
      Kafka__ConsumerTopic: "user-registered"
      Kafka__ConsumerGroupId: "gestion-clubs-group"
      Kafka__ProducerTopicMember: "user-promoted-to-club-member"
      Kafka__ClubsTopic: "clubs-topic"
      Kafka__AnnouncementsTopic: "announcements-topic"
      Kafka__EventsTopic: "events-topic"
      ConnectionStrings__DefaultConnection: "Server=sqlserver-clubs;Database=GestionClubs;User Id=sa;Password=YourStr0ngP@ssword!;TrustServerCertificate=True;"
      IdentityProvider__Authority: "https://identityprovider:8443"
      IdentityProvider__Issuer: "myapp"
      IdentityProvider__Audience: "myappusers"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:8081;http://+:8080"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.crt"
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: "/https/aspnetapp.key"
    volumes:
      - ./certs:/https:ro

  apigateway:
    build:
      context: ./ApiGateway/ApiGateway
      dockerfile: ApiGateway/Dockerfile
    image: mbokri/apigateway:latest
    ports:
      - "5000:8080"   # HTTP
      - "5001:8081"   # HTTPS
    depends_on:
      identityprovider:
        condition: service_started
      gestionclubs:
        condition: service_started
      chatbot:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:8081;http://+:8080"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.crt"
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: "/https/aspnetapp.key"
    volumes:
      - ./certs:/https:ro
      

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      kafka:
        condition: service_healthy

  postgres-chatbot:
    image: pgvector/pgvector:pg16
    container_name: uniclubs-postgres
    environment:
      POSTGRES_USER: uniclubs
      POSTGRES_PASSWORD: uniclubs
      POSTGRES_DB: uniclubs
    ports:
      - "5432:5432"
    volumes:
      - pgdata-chatbot:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uniclubs"]
      interval: 5s
      timeout: 5s
      retries: 5

  chatbot:
    build:
      context: ./Chatbot
      dockerfile: Dockerfile
    image: mbokri/chatbot:latest
    container_name: uniclubs-chatbot
    ports:
      - "8083:8083"
    depends_on:
      postgres-chatbot:
        condition: service_healthy
      init-kafka:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "postgresql+psycopg://uniclubs:uniclubs@postgres-chatbot:5432/uniclubs"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      KAFKA_ENABLED: "true"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      KAFKA_CONSUMER_GROUP_ID: "chatbot-group"
      IDP_JWKS_URL: "https://identityprovider:8443/.well-known/jwks"
      IDP_VERIFY_SSL: "false"
      JWT_ISSUER: "myapp"
      JWT_AUDIENCE: "myappusers"
      CHROMA_PATH: "/app/chroma_data"
    volumes:
      - chroma-data:/app/chroma_data
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - mynw
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mynw

networks:
  mynw:
  
volumes:
  sqldata-idp:
  sqldata-clubs:
  keys:
  pgdata-chatbot:
  chroma-data:
  grafana-data: