services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStr0ngP@ssword!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  identityprovider:
    image: mbokri/identityprovider:latest
    ports:
      - "8080:8080"   # HTTP (optionnel, tu peux l'enlever)
      - "8443:8443"   # HTTPS
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=IdentityProvider;User Id=sa;Password=YourStr0ngP@ssword!;TrustServerCertificate=True;"
      JwtOptions__Secret: "votre-secret-de-production-suffisamment-long"
      JwtOptions__Issuer: "myapp"
      JwtOptions__Audience: "myappusers"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:8443;http://+:8080"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.crt"
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: "/https/aspnetapp.key"
    volumes:
      - keys:/app/keys
      - ./certs:/https:ro # monte le certificat dans le container

  gestionclubs:
    build:
      context: ./GestionClubs
      dockerfile: GestionClubs/Dockerfile
    ports:
      - "8081:8081"   # HTTPS
      - "8082:8080"   # HTTP
    depends_on:
      - sqlserver
      - identityprovider
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=GestionClubs;User Id=sa;Password=YourStr0ngP@ssword!;TrustServerCertificate=True;"
      IdentityProvider__Authority: "https://identityprovider:8443"
      IdentityProvider__Issuer: "myapp"
      IdentityProvider__Audience: "myappusers"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:8081;http://+:8080"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.crt"
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: "/https/aspnetapp.key"
    volumes:
      - ./certs:/https:ro

volumes:
  sqldata:
  keys: